import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        {/* will add the favicon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl text-center font-bold my-4 font-mono tracking-tighter capitalize">
      hello trying tailwind and Next.js today
    </h1>
    </div>
  )
}

export default Home
